### ISSUE TITLE
Week 8 Review Ticket

### ISSUE THREAD

**Issue by shrutiapcsp** [gigiguan/python#8]
28 comments total
Backlog items:
- changing background on front page to be easier to look
- lighter color for page UI
- change fonts for some pages
College board work: 3/3 for all members (Shruti Chari, Gigi Guan, Neha Valluri, Jessie Park)
Total points from Mr. M: 4.5/5

**FINAL GRADE FOR ALL: 7.5/8**

**Comment by Ritvik-Keerthi** [comment]
One thing I liked was the animations in your presentation, making it more attractive to watch. As for the website in particular, I think that the core subjects split was a good idea, as it helps the user get to exactly what subject they want, rather than having to not be able to choose. 

One thing you could improve on would be the css color, as it is a bit hard to see the words with the del norte logo as the background.

**Comment by Rebecca-123** [comment]
**Positives**
1. Great intro, explanation of ideation and website plan
2. Nice implementation of greetings technical
3. README is organized with tasks and connected to Scrum Board

**Improvements**
1. Different background for home page (one DN symbol), add more content to about pages

**Comment by Stanleyy03840** [comment]
positive: lots of information for each course with a drop down menu that sorts them into subjects.
improvements: make hte page more interactive with space for user input. text on homescreen also a little hard to read

**Comment by christinlee367** [comment]
positives:
- Nice introduction
- goals for now to the night of the museum are stated clearly as tangibles
Improvements:
- I feel the the theme of the background of the homepage is a bit too "flowery" and distracting

**Comment by TheRadRabbidRabbit** [comment]
+ Information is well presented
+ Website is very relatable towards students
+ Cool and unique website
- Wallpaper colors kind of bland

**Comment by NathanShih04** [comment]
+Very good idea and creative implementation
+Graphic design is pleasant
+Wireframe looks good
-Make text easier to read
